const List<Map<String, String>> kCountries = [
  {'name': 'Afghanistan', 'flag': '🇦🇫'},
  {'name': 'Albania', 'flag': '🇦🇱'},
  {'name': 'Algeria', 'flag': '🇩🇿'},
  {'name': 'Argentina', 'flag': '🇦🇷'},
  {'name': 'Australia', 'flag': '🇦🇺'},
  {'name': 'Austria', 'flag': '🇦🇹'},
  {'name': 'Bangladesh', 'flag': '🇧🇩'},
  {'name': 'Belgium', 'flag': '🇧🇪'},
  {'name': 'Bolivia', 'flag': '🇧🇴'},
  {'name': 'Brazil', 'flag': '🇧🇷'},
  {'name': 'Canada', 'flag': '🇨🇦'},
  {'name': 'Chile', 'flag': '🇨🇱'},
  {'name': 'China', 'flag': '🇨🇳'},
  {'name': 'Colombia', 'flag': '🇨🇴'},
  {'name': 'Croatia', 'flag': '🇭🇷'},
  {'name': 'Czech Republic', 'flag': '🇨🇿'},
  {'name': 'Denmark', 'flag': '🇩🇰'},
  {'name': 'Ecuador', 'flag': '🇪🇨'},
  {'name': 'Egypt', 'flag': '🇪🇬'},
  {'name': 'Ethiopia', 'flag': '🇪🇹'},
  {'name': 'Finland', 'flag': '🇫🇮'},
  {'name': 'France', 'flag': '🇫🇷'},
  {'name': 'Germany', 'flag': '🇩🇪'},
  {'name': 'Ghana', 'flag': '🇬🇭'},
  {'name': 'Greece', 'flag': '🇬🇷'},
  {'name': 'Hungary', 'flag': '🇭🇺'},
  {'name': 'India', 'flag': '🇮🇳'},
  {'name': 'Indonesia', 'flag': '🇮🇩'},
  {'name': 'Iran', 'flag': '🇮🇷'},
  {'name': 'Iraq', 'flag': '🇮🇶'},
  {'name': 'Ireland', 'flag': '🇮🇪'},
  {'name': 'Israel', 'flag': '🇮🇱'},
  {'name': 'Italy', 'flag': '🇮🇹'},
  {'name': 'Japan', 'flag': '🇯🇵'},
  {'name': 'Jordan', 'flag': '🇯🇴'},
  {'name': 'Kenya', 'flag': '🇰🇪'},
  {'name': 'Malaysia', 'flag': '🇲🇾'},
  {'name': 'Mexico', 'flag': '🇲🇽'},
  {'name': 'Morocco', 'flag': '🇲🇦'},
  {'name': 'Netherlands', 'flag': '🇳🇱'},
  {'name': 'New Zealand', 'flag': '🇳🇿'},
  {'name': 'Nigeria', 'flag': '🇳🇬'},
  {'name': 'Norway', 'flag': '🇳🇴'},
  {'name': 'Pakistan', 'flag': '🇵🇰'},
  {'name': 'Peru', 'flag': '🇵🇪'},
  {'name': 'Philippines', 'flag': '🇵🇭'},
  {'name': 'Poland', 'flag': '🇵🇱'},
  {'name': 'Portugal', 'flag': '🇵🇹'},
  {'name': 'Romania', 'flag': '🇷🇴'},
  {'name': 'Russia', 'flag': '🇷🇺'},
  {'name': 'Saudi Arabia', 'flag': '🇸🇦'},
  {'name': 'Serbia', 'flag': '🇷🇸'},
  {'name': 'Singapore', 'flag': '🇸🇬'},
  {'name': 'South Africa', 'flag': '🇿🇦'},
  {'name': 'South Korea', 'flag': '🇰🇷'},
  {'name': 'Spain', 'flag': '🇪🇸'},
  {'name': 'Sri Lanka', 'flag': '🇱🇰'},
  {'name': 'Sweden', 'flag': '🇸🇪'},
  {'name': 'Switzerland', 'flag': '🇨🇭'},
  {'name': 'Taiwan', 'flag': '🇹🇼'},
  {'name': 'Thailand', 'flag': '🇹🇭'},
  {'name': 'Turkey', 'flag': '🇹🇷'},
  {'name': 'Ukraine', 'flag': '🇺🇦'},
  {'name': 'United Arab Emirates', 'flag': '🇦🇪'},
  {'name': 'United Kingdom', 'flag': '🇬🇧'},
  {'name': 'United States', 'flag': '🇺🇸'},
  {'name': 'Venezuela', 'flag': '🇻🇪'},
  {'name': 'Vietnam', 'flag': '🇻🇳'},
];